### ISSUE TITLE
Adjacent genes tool

### ISSUE THREAD

**Issue by RyYoung** [TAMU-CPT/galaxy-tools#24]
Karthik and I are studying the LydA-LydB holin-antiholin proteins of phage P1.  These genes are always adjacent.  
I need a tool that takes a protein record, finds the associated nucleotide record and then pulls the CDS (aa) sequence from the adjacent CDS, either upstream or downstream.  Ideally it would ask for upstream or downstream and in the perfect world, ask how many adjacent CDSs to fetch.  (i.e., 2 upstream, 3 downstream, maybe option for both.)

Need of course doesnt mean it is possible.  

As I understand it there may be more than one nt record for a protein record but that is ok.  It could just go to the top one, fetch the adjacent CDS according to spec, and then report the locus tag of the nt record accessed.

**Comment by RyYoung** [comment]
This tool is going to be generally useful because lysis genes are frequently clustered.

**Comment by MoffMade** [comment]
Shouldn't be too difficult to pull X upstream CDSs and Y downstream CDSs from a parsed record. What formats would you expect the input protein/nucleotide records to be?

**Comment by MoffMade** [comment]
As discussed in person:

1) protein id input should be a list of unique identifiers to fetch genbank files from NCBI
2) selectors for # of genes upstream and downstream of provided protein id
3) selector for output type (list of surrounding ids or full genbank information for each surrounding ID

**Comment by MoffMade** [comment]
Put On Hold as this may be bundled into a 491 Project.

**Comment by jrr-cpt** [comment]
This is a tool we want to use in the disruptin finder workflow as well. And it would be useful for looking at releasins. 

The intron detection tool has some code that may be helpful in constructing this. It only keeps matches if they are within 10 CDSs.

**Comment by MoffMade** [comment]
@BeaverThing was this completed with the Adjacent Features/Adjacent Features with Overlap tools?

**Comment by jrr-cpt** [comment]
complete with Adjacent features tool
